### ISSUE TITLE
Fix TypeError ctrlKey warning

### ISSUE THREAD

**Issue by DataGridXL** [DataGridXL/DataGridXL2#37]
```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'ctrlKey')
at move (datagridxl2.js:8:96248)     at <anonymous> (datagridxl2.js:8:104181)     at uo (datagridxl2.js:8:77401)
```

Ticket /198

**Comment by DataGridXL** [comment]
Fixed in new update v2.22.07.30
